[versions]
# libraries
annotations = "24.0.1"

# plugins
gradleIntelliJPlugin = "1.17.3"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }

