[versions]
# libraries
annotations = "24.0.1"

# plugins
gradleIntelliJPlatformPlugin = "2.0.0-beta1"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
gradleIntelliJPlatformPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlatformPlugin" }
gradleIntelliJPlatformMigrationPlugin = { id = "org.jetbrains.intellij.platform.migration", version.ref = "gradleIntelliJPlatformPlugin" }